# PyTorch Intro

In [1]:
import torch
import numpy as np

In [2]:
torch.empty(5,3)
torch.rand(2,4)
torch.zeros(5,6,dtype=torch.long)

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])

In [3]:
x = torch.tensor([8,4,3])

In [4]:
# y = torch.randn_like(x,dtype=torch.long)
y = x.type(torch.FloatTensor)

In [5]:
torch.cuda.device_count()

0

In [6]:
y = torch.rand(3,1)
# y = y.cuda()
x+y

RuntimeError: expected backend CPU and dtype Float but got backend CPU and dtype Long

In [6]:
# convert numpy to tensor or vise versa
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print(
    '\nnumpy array:', np_data,          # [[0 1 2], [3 4 5]]
    '\ntorch tensor:', torch_data,      #  0  1  2 \n 3  4  5    [torch.LongTensor of size 2x3]
    '\ntensor to array:', tensor2array, # [[0 1 2], [3 4 5]]
)


numpy array: [[0 1 2]
 [3 4 5]] 
torch tensor: tensor([[0, 1, 2],
        [3, 4, 5]]) 
tensor to array: [[0 1 2]
 [3 4 5]]


In [ ]:
Link to [Notebook 2](.ipynb)